import React, { useState, useEffect, useRef, useCallback } from 'react';
import { 
  Sparkles, Download, Upload, RefreshCw, Save, 
  Palette, Eye, EyeOff, Layers, Wand2,
  Move, Maximize2, Minimize2, Play, Pause,
  Code, Copy, Terminal, Bot, User, Smile
} from 'lucide-react';
import { Button } from '../ui/button';

// Avatar part libraries (these map to dicebear or similar APIs)
const AVATAR_STYLES = {
  adventurer: { name: 'Adventurer', source: 'dicebear', colors: true },
  avataaars: { name: 'Avataaars', source: 'dicebear', colors: true },
  bottts: { name: 'Bots', source: 'dicebear', colors: false },
  funEmoji: { name: 'Fun Emoji', source: 'dicebear', colors: false },
  lorelei: { name: 'Lorelei', source: 'dicebear', colors: true },
  notionists: { name: 'Notionists', source: 'dicebear', colors: true },
  pixelArt: { name: 'Pixel Art', source: 'dicebear', colors: true },
};

// Animation behaviors for the floating avatar
const BEHAVIORS = {
  idle: {
    name: 'Idle',
    description: 'Float gently in place',
    animation: 'float',
    movement: 'none'
  },
  wander: {
    name: 'Wander',
    description: 'Roam around the screen',
    animation: 'float',
    movement: 'random'
  },
  follow: {
    name: 'Follow Cursor',
    description: 'Follow your mouse',
    animation: 'bounce',
    movement: 'cursor'
  },
  orbit: {
    name: 'Orbit',
    description: 'Circle around center',
    animation: 'spin',
    movement: 'orbit'
  },
  bounce: {
    name: 'Bounce',
    description: 'Bounce around edges',
    animation: 'bounce',
    movement: 'bounce'
  },
  sleep: {
    name: 'Sleep',
    description: 'Take a nap',
    animation: 'breathe',
    movement: 'none'
  }
};

// Avatar configuration options
const AVATAR_OPTIONS = {
  adventurer: ['seed', 'backgroundColor', 'skinColor', 'hairColor', 'accessories'],
  avataaars: ['seed', 'backgroundColor', 'skin', 'top', 'hairColor', 'facialHair', 'clothes', 'eyes', 'eyebrows', 'mouth', 'accessories'],
  bottts: ['seed', 'backgroundColor', 'colors'],
  pixelArt: ['seed', 'backgroundColor', 'color1', 'color2', 'color3', 'color4', 'color5'],
};

// Generate avatar URL from dicebear API
const generateAvatarUrl = (style, options) => {
  const baseUrl = `https://api.dicebear.com/7.x/${style}/svg`;
  const params = new URLSearchParams();
  
  Object.entries(options).forEach(([key, value]) => {
    if (value && value !== 'random') {
      params.append(key, value);
    }
  });
  
  return `${baseUrl}?${params.toString()}`;
};

// Python code generator for the floating avatar
const generatePythonCode = (config) => {
  return `# NovAura Living Avatar - Python Desktop Pet
# Generated by Avatar Creator

import tkinter as tk
from tkinter import Canvas
import random
import math
import time
import threading
from PIL import Image, ImageTk
import requests
from io import BytesIO

class LivingAvatar:
    def __init__(self, root):
        self.root = root
        self.root.overrideredirect(True)  # No window borders
        self.root.attributes('-topmost', True)  # Always on top
        self.root.attributes('-transparentcolor', 'white')  # Transparent bg
        
        self.size = ${config.size || 120}
        self.behavior = "${config.behavior || 'wander'}"
        self.speed = ${config.speed || 2}
        
        # Load avatar image
        self.canvas = Canvas(root, width=self.size, height=self.size, 
                           bg='white', highlightthickness=0)
        self.canvas.pack()
        
        # Download and display avatar
        self.load_avatar()
        
        # Animation state
        self.x = random.randint(100, 800)
        self.y = random.randint(100, 600)
        self.vx = random.choice([-1, 1]) * self.speed
        self.vy = random.choice([-1, 1]) * self.speed
        self.target_x = None
        self.target_y = None
        
        # Interaction state
        self.mood = "happy"
        self.energy = 100
        self.hunger = 0
        
        # Start animation
        self.animate()
        self.behavior_thread = threading.Thread(target=self.behavior_loop, daemon=True)
        self.behavior_thread.start()
        
        # Bind interactions
        self.canvas.bind("<Button-1>", self.on_click)
        self.canvas.bind("<B1-Motion>", self.on_drag)
        self.root.bind("<Double-Button-1>", self.interact)
    
    def load_avatar(self):
        """Load avatar from URL or local file"""
        try:
            url = "${config.avatarUrl || ''}"
            if url:
                response = requests.get(url)
                image = Image.open(BytesIO(response.content))
                image = image.resize((self.size, self.size), Image.Resampling.LANCZOS)
                self.photo = ImageTk.PhotoImage(image)
                self.avatar_id = self.canvas.create_image(
                    self.size//2, self.size//2, image=self.photo
                )
        except Exception as e:
            print(f"Error loading avatar: {e}")
            # Fallback: Draw simple circle
            self.canvas.create_oval(10, 10, self.size-10, self.size-10, 
                                  fill='#4ade80', outline='#22c55e', width=3)
    
    def animate(self):
        """Main animation loop"""
        if self.behavior == 'wander':
            self.wander_behavior()
        elif self.behavior == 'follow':
            self.follow_behavior()
        elif self.behavior == 'bounce':
            self.bounce_behavior()
        elif self.behavior == 'orbit':
            self.orbit_behavior()
        
        # Floating animation
        offset = math.sin(time.time() * 2) * 5
        self.root.geometry(f"{self.size}x{self.size}+{int(self.x)}+{int(self.y + offset)}")
        
        self.root.after(16, self.animate)  # ~60 FPS
    
    def wander_behavior(self):
        """Random wandering movement"""
        self.x += self.vx
        self.y += self.vy
        
        # Screen bounds
        screen_w = self.root.winfo_screenwidth()
        screen_h = self.root.winfo_screenheight()
        
        if self.x <= 0 or self.x >= screen_w - self.size:
            self.vx *= -1
        if self.y <= 0 or self.y >= screen_h - self.size:
            self.vy *= -1
        
        # Random direction change
        if random.random() < 0.02:
            self.vx = random.choice([-1, 1]) * self.speed
            self.vy = random.choice([-1, 1]) * self.speed
    
    def follow_behavior(self):
        """Follow mouse cursor"""
        mouse_x = self.root.winfo_pointerx()
        mouse_y = self.root.winfo_pointery()
        
        dx = mouse_x - self.x - self.size//2
        dy = mouse_y - self.y - self.size//2
        distance = math.sqrt(dx**2 + dy**2)
        
        if distance > 50:
            self.vx = (dx / distance) * self.speed
            self.vy = (dy / distance) * self.speed
            self.x += self.vx
            self.y += self.vy
    
    def bounce_behavior(self):
        """Bounce off screen edges"""
        self.x += self.vx
        self.y += self.vy
        
        screen_w = self.root.winfo_screenwidth()
        screen_h = self.root.winfo_screenheight()
        
        if self.x <= 0 or self.x >= screen_w - self.size:
            self.vx *= -1
            self.bounce_animation()
        if self.y <= 0 or self.y >= screen_h - self.size:
            self.vy *= -1
            self.bounce_animation()
    
    def orbit_behavior(self):
        """Orbit around screen center"""
        center_x = self.root.winfo_screenwidth() // 2
        center_y = self.root.winfo_screenheight() // 2
        radius = 200
        angle = time.time() * self.speed * 0.5
        
        self.x = center_x + math.cos(angle) * radius - self.size//2
        self.y = center_y + math.sin(angle) * radius - self.size//2
    
    def bounce_animation(self):
        """Squash and stretch on bounce"""
        # Could add visual squash effect here
        pass
    
    def behavior_loop(self):
        """Background behavior processing"""
        while True:
            time.sleep(5)
            
            # Random mood changes
            if random.random() < 0.1:
                self.mood = random.choice(['happy', 'curious', 'sleepy', 'excited'])
                print(f"Avatar is feeling {self.mood}")
            
            # Energy depletion
            self.energy = max(0, self.energy - 1)
            if self.energy < 20:
                self.mood = 'tired'
    
    def on_click(self, event):
        """Handle click"""
        self.drag_data = {'x': event.x, 'y': event.y}
        self.interact()
    
    def on_drag(self, event):
        """Handle dragging"""
        if hasattr(self, 'drag_data'):
            dx = event.x - self.drag_data['x']
            dy = event.y - self.drag_data['y']
            self.x += dx
            self.y += dy
    
    def interact(self, event=None):
        """User interaction"""
        reactions = {
            'happy': ['*jumps happily*', '*spins around*', '*waves*'],
            'curious': ['*tilts head*', '*looks around*', '*sniffs*'],
            'sleepy': ['*yawns*', '*rubs eyes*', '*curls up*'],
            'excited': ['*does a flip*', '*runs in circles*', '*cheers*'],
            'tired': ['*slow blink*', '*rests*', '*sighs*']
        }
        
        reaction = random.choice(reactions.get(self.mood, ['*waves*']))
        print(f"Avatar: {reaction}")
        
        # Boost energy on interaction
        self.energy = min(100, self.energy + 10)

# Launch avatar
def main():
    root = tk.Tk()
    root.title("NovAura Living Avatar")
    
    avatar = LivingAvatar(root)
    root.mainloop()

if __name__ == "__main__":
    main()
`;
};

// JavaScript floating avatar for web
const generateJSCode = (config) => {
  return `// NovAura Living Avatar - Web Version
// Add this script to your page

class LivingAvatar {
  constructor(options = {}) {
    this.size = options.size || ${config.size || 120};
    this.behavior = options.behavior || '${config.behavior || 'wander'}';
    this.speed = options.speed || ${config.speed || 2};
    this.avatarUrl = options.avatarUrl || '${config.avatarUrl || ''}';
    
    this.x = Math.random() * (window.innerWidth - this.size);
    this.y = Math.random() * (window.innerHeight - this.size);
    this.vx = (Math.random() - 0.5) * this.speed;
    this.vy = (Math.random() - 0.5) * this.speed;
    
    this.createElement();
    this.startAnimation();
    
    // Mood system
    this.mood = 'happy';
    this.energy = 100;
    setInterval(() => this.updateMood(), 5000);
  }
  
  createElement() {
    this.el = document.createElement('div');
    this.el.className = 'living-avatar';
    this.el.innerHTML = \`
      <img src="\${this.avatarUrl}" alt="Avatar" 
           style="width:100%;height:100%;pointer-events:none;" />
      <div class="avatar-mood" style="position:absolute;bottom:-20px;left:50%;transform:translateX(-50%);
                                       font-size:20px;opacity:0;transition:opacity 0.3s;"></div>
    \`;
    
    Object.assign(this.el.style, {
      position: 'fixed',
      width: this.size + 'px',
      height: this.size + 'px',
      zIndex: '9999',
      cursor: 'pointer',
      filter: 'drop-shadow(0 4px 12px rgba(0,0,0,0.3))',
      transition: 'transform 0.1s ease-out',
      userSelect: 'none'
    });
    
    // Interactions
    this.el.addEventListener('click', () => this.interact());
    this.el.addEventListener('mousedown', (e) => this.startDrag(e));
    
    document.body.appendChild(this.el);
  }
  
  startAnimation() {
    const animate = () => {
      switch(this.behavior) {
        case 'wander': this.wander(); break;
        case 'follow': this.follow(); break;
        case 'bounce': this.bounce(); break;
        case 'orbit': this.orbit(); break;
        case 'idle': this.idle(); break;
      }
      
      // Floating effect
      const float = Math.sin(Date.now() / 500) * 5;
      this.el.style.transform = \`translate(\${this.x}px, \${this.y + float}px)\`;
      
      requestAnimationFrame(animate);
    };
    animate();
  }
  
  wander() {
    this.x += this.vx;
    this.y += this.vy;
    
    // Bounds check
    if (this.x <= 0 || this.x >= window.innerWidth - this.size) this.vx *= -1;
    if (this.y <= 0 || this.y >= window.innerHeight - this.size) this.vy *= -1;
    
    // Random direction change
    if (Math.random() < 0.02) {
      this.vx = (Math.random() - 0.5) * this.speed;
      this.vy = (Math.random() - 0.5) * this.speed;
    }
  }
  
  follow() {
    // Implement cursor following
    if (!this.targetX) return;
    const dx = this.targetX - this.x - this.size/2;
    const dy = this.targetY - this.y - this.size/2;
    const dist = Math.sqrt(dx*dx + dy*dy);
    
    if (dist > 50) {
      this.vx = (dx / dist) * this.speed;
      this.vy = (dy / dist) * this.speed;
      this.x += this.vx;
      this.y += this.vy;
    }
  }
  
  bounce() {
    this.x += this.vx;
    this.y += this.vy;
    
    if (this.x <= 0 || this.x >= window.innerWidth - this.size) {
      this.vx *= -1;
      this.showMood('💥');
    }
    if (this.y <= 0 || this.y >= window.innerHeight - this.size) {
      this.vy *= -1;
      this.showMood('💥');
    }
  }
  
  orbit() {
    const centerX = window.innerWidth / 2;
    const centerY = window.innerHeight / 2;
    const time = Date.now() / 1000;
    const radius = 200;
    
    this.x = centerX + Math.cos(time * this.speed * 0.5) * radius - this.size/2;
    this.y = centerY + Math.sin(time * this.speed * 0.5) * radius - this.size/2;
  }
  
  idle() {
    // Gentle breathing animation
    const breathe = 1 + Math.sin(Date.now() / 1000) * 0.05;
    this.el.querySelector('img').style.transform = \`scale(\${breathe})\`;
  }
  
  interact() {
    const reactions = {
      happy: ['🎉', '😊', '✨'],
      curious: ['🤔', '👀', '❓'],
      sleepy: ['😴', '💤', '🥱'],
      excited: ['🤩', '🎊', '🚀']
    };
    
    const emoji = reactions[this.mood][Math.floor(Math.random() * 3)];
    this.showMood(emoji);
    this.energy = Math.min(100, this.energy + 10);
    
    // Jump animation
    this.el.style.animation = 'none';
    setTimeout(() => {
      this.el.style.animation = 'avatarJump 0.5s ease-out';
    }, 10);
  }
  
  showMood(emoji) {
    const moodEl = this.el.querySelector('.avatar-mood');
    moodEl.textContent = emoji;
    moodEl.style.opacity = '1';
    setTimeout(() => moodEl.style.opacity = '0', 2000);
  }
  
  updateMood() {
    this.energy = Math.max(0, this.energy - 1);
    
    if (this.energy > 70) this.mood = 'excited';
    else if (this.energy > 40) this.mood = 'happy';
    else if (this.energy > 20) this.mood = 'sleepy';
    else this.mood = 'tired';
  }
  
  startDrag(e) {
    const startX = e.clientX - this.x;
    const startY = e.clientY - this.y;
    
    const onMove = (e) => {
      this.x = e.clientX - startX;
      this.y = e.clientY - startY;
      this.behavior = 'dragged';
    };
    
    const onUp = () => {
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
      this.behavior = '${config.behavior || 'wander'}';
    };
    
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
  }
}

// CSS Animation
const style = document.createElement('style');
style.textContent = \`
  @keyframes avatarJump {
    0%, 100% { transform: translateY(0) scale(1); }
    50% { transform: translateY(-30px) scale(1.1); }
  }
  .living-avatar:hover {
    filter: drop-shadow(0 6px 20px rgba(0,217,255,0.4)) !important;
  }
\`;
document.head.appendChild(style);

// Initialize
window.myAvatar = new LivingAvatar({
  avatarUrl: '${config.avatarUrl || ''}',
  behavior: '${config.behavior || 'wander'}',
  size: ${config.size || 120}
});
`;
};

export default function LivingAvatarCreator({ onAIChat }) {
  const [style, setStyle] = useState('adventurer');
  const [options, setOptions] = useState({ seed: 'Nova', backgroundColor: 'b6e3f4' });
  const [behavior, setBehavior] = useState('wander');
  const [size, setSize] = useState(120);
  const [speed, setSpeed] = useState(2);
  const [avatarUrl, setAvatarUrl] = useState('');
  const [activeTab, setActiveTab] = useState('create');
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Generate preview on option change
  useEffect(() => {
    const url = generateAvatarUrl(style, options);
    setAvatarUrl(url);
  }, [style, options]);

  const randomize = () => {
    setOptions({
      ...options,
      seed: Math.random().toString(36).substring(7),
    });
  };

  const generateWithAI = async () => {
    if (!onAIChat) return;
    setIsGenerating(true);
    
    try {
      const prompt = `Create a detailed character description for an avatar seed: ${options.seed}. Describe appearance, personality, and style.`;
      const result = await onAIChat(prompt, 'creative');
      
      // Use response to influence options
      setOptions({ ...options, seed: result?.response?.slice(0, 20) || Math.random().toString(36).substring(7) });
    } catch (e) {
      randomize();
    }
    
    setIsGenerating(false);
  };

  const downloadPython = () => {
    const code = generatePythonCode({ avatarUrl, behavior, size, speed });
    const blob = new Blob([code], { type: 'text/plain' });
    const link = document.createElement('a');
    link.download = 'living_avatar.py';
    link.href = URL.createObjectURL(blob);
    link.click();
  };

  const downloadJS = () => {
    const code = generateJSCode({ avatarUrl, behavior, size, speed });
    const blob = new Blob([code], { type: 'text/javascript' });
    const link = document.createElement('a');
    link.download = 'living_avatar.js';
    link.href = URL.createObjectURL(blob);
    link.click();
  };

  return (
    <div className="h-full flex flex-col bg-slate-950 text-white overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2 bg-gradient-to-r from-purple-900/30 to-slate-900 border-b border-slate-800 shrink-0">
        <div className="flex items-center gap-2">
          <Smile className="w-4 h-4 text-purple-400" />
          <span className="text-sm font-semibold">Living Avatar Creator</span>
        </div>
        <div className="flex gap-1">
          <button onClick={downloadPython} className="px-2 py-1 rounded bg-blue-600/30 text-blue-300 text-xs flex items-center gap-1 hover:bg-blue-600/50">
            <Terminal className="w-3 h-3" /> Python
          </button>
          <button onClick={downloadJS} className="px-2 py-1 rounded bg-yellow-600/30 text-yellow-300 text-xs flex items-center gap-1 hover:bg-yellow-600/50">
            <Code className="w-3 h-3" /> JS
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-800">
        <button 
          onClick={() => setActiveTab('create')}
          className={`flex-1 py-2 text-xs font-medium flex items-center justify-center gap-1 ${activeTab === 'create' ? 'bg-purple-600/20 text-purple-300 border-b-2 border-purple-500' : 'text-slate-400 hover:bg-slate-800'}`}
        >
          <Palette className="w-3 h-3" /> Design
        </button>
        <button 
          onClick={() => setActiveTab('behavior')}
          className={`flex-1 py-2 text-xs font-medium flex items-center justify-center gap-1 ${activeTab === 'behavior' ? 'bg-purple-600/20 text-purple-300 border-b-2 border-purple-500' : 'text-slate-400 hover:bg-slate-800'}`}
        >
          <Bot className="w-3 h-3" /> Behavior
        </button>
        <button 
          onClick={() => setActiveTab('code')}
          className={`flex-1 py-2 text-xs font-medium flex items-center justify-center gap-1 ${activeTab === 'code' ? 'bg-purple-600/20 text-purple-300 border-b-2 border-purple-500' : 'text-slate-400 hover:bg-slate-800'}`}
        >
          <Code className="w-3 h-3" /> Export
        </button>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Left Panel */}
        <div className="w-56 border-r border-slate-800 p-3 space-y-4 overflow-y-auto shrink-0">
          
          {activeTab === 'create' && (
            <>
              {/* Style Selection */}
              <div>
                <label className="text-[9px] text-slate-500 block mb-1.5 uppercase">Avatar Style</label>
                <div className="space-y-1">
                  {Object.entries(AVATAR_STYLES).map(([id, info]) => (
                    <button
                      key={id}
                      onClick={() => setStyle(id)}
                      className={`w-full text-left px-2 py-1.5 rounded text-xs flex items-center gap-2 transition-colors ${
                        style === id ? 'bg-purple-600/30 text-purple-300' : 'text-slate-400 hover:bg-slate-800'
                      }`}
                    >
                      <User className="w-3 h-3" />
                      {info.name}
                    </button>
                  ))}
                </div>
              </div>

              {/* Seed/Name */}
              <div>
                <label className="text-[9px] text-slate-500 block mb-1.5 uppercase">Seed/Name</label>
                <div className="flex gap-1">
                  <input
                    value={options.seed}
                    onChange={(e) => setOptions({...options, seed: e.target.value})}
                    className="flex-1 px-2 py-1 bg-black/30 border border-slate-700 rounded text-xs"
                  />
                  <button onClick={randomize} className="p-1 bg-slate-800 rounded hover:bg-slate-700">
                    <RefreshCw className="w-3 h-3" />
                  </button>
                </div>
              </div>

              {/* AI Generate */}
              <button
                onClick={generateWithAI}
                disabled={isGenerating}
                className="w-full py-2 bg-gradient-to-r from-purple-600/50 to-pink-600/50 rounded text-xs flex items-center justify-center gap-1.5 hover:opacity-90 disabled:opacity-50"
              >
                <Wand2 className={`w-3 h-3 ${isGenerating ? 'animate-spin' : ''}`} />
                {isGenerating ? 'Generating...' : 'AI Generate'}
              </button>
            </>
          )}

          {activeTab === 'behavior' && (
            <>
              {/* Behavior Selection */}
              <div>
                <label className="text-[9px] text-slate-500 block mb-1.5 uppercase">Movement Behavior</label>
                <div className="space-y-1">
                  {Object.entries(BEHAVIORS).map(([id, info]) => (
                    <button
                      key={id}
                      onClick={() => setBehavior(id)}
                      className={`w-full text-left px-2 py-1.5 rounded text-xs transition-colors ${
                        behavior === id ? 'bg-purple-600/30 text-purple-300' : 'text-slate-400 hover:bg-slate-800'
                      }`}
                    >
                      <div className="font-medium">{info.name}</div>
                      <div className="text-[9px] opacity-70">{info.description}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Size Slider */}
              <div>
                <label className="text-[9px] text-slate-500 block mb-1.5 uppercase">Size: {size}px</label>
                <input
                  type="range"
                  min="64"
                  max="256"
                  value={size}
                  onChange={(e) => setSize(parseInt(e.target.value))}
                  className="w-full"
                />
              </div>

              {/* Speed Slider */}
              <div>
                <label className="text-[9px] text-slate-500 block mb-1.5 uppercase">Speed: {speed}x</label>
                <input
                  type="range"
                  min="1"
                  max="10"
                  value={speed}
                  onChange={(e) => setSpeed(parseInt(e.target.value))}
                  className="w-full"
                />
              </div>
            </>
          )}

          {activeTab === 'code' && (
            <>
              <div className="p-3 bg-black/30 rounded border border-slate-700">
                <h4 className="text-xs font-medium mb-2">Export Options</h4>
                <p className="text-[10px] text-slate-400 mb-3">
                  Export your avatar as a living desktop pet!
                </p>
                <div className="space-y-2">
                  <button onClick={downloadPython} className="w-full py-2 bg-blue-600/30 hover:bg-blue-600/50 rounded text-xs flex items-center justify-center gap-2">
                    <Download className="w-3 h-3" /> Download Python (.py)
                  </button>
                  <button onClick={downloadJS} className="w-full py-2 bg-yellow-600/30 hover:bg-yellow-600/50 rounded text-xs flex items-center justify-center gap-2">
                    <Download className="w-3 h-3" /> Download JavaScript (.js)
                  </button>
                </div>
              </div>

              <div className="p-3 bg-black/30 rounded border border-slate-700">
                <h4 className="text-xs font-medium mb-2">How to Use</h4>
                <div className="text-[10px] text-slate-400 space-y-1">
                  <p><strong>Python:</strong> Run with <code>python living_avatar.py</code></p>
                  <p><strong>JavaScript:</strong> Include in HTML or paste in console</p>
                </div>
              </div>
            </>
          )}
        </div>

        {/* Preview Area */}
        <div className="flex-1 flex flex-col items-center justify-center bg-gradient-to-br from-slate-900 via-slate-950 to-black relative overflow-hidden">
          {/* Grid background */}
          <div className="absolute inset-0 opacity-10" style={{
            backgroundImage: 'linear-gradient(rgba(147, 51, 234, 0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(147, 51, 234, 0.3) 1px, transparent 1px)',
            backgroundSize: '50px 50px'
          }} />
          
          {/* Avatar Preview */}
          <div 
            className="relative z-10 transition-all duration-300"
            style={{
              width: size,
              height: size,
              animation: behavior === 'idle' ? 'float 3s ease-in-out infinite' : 
                        behavior === 'bounce' ? 'bounce 1s ease-in-out infinite' :
                        behavior === 'orbit' ? 'spin 4s linear infinite' : 'none'
            }}
          >
            {avatarUrl ? (
              <img 
                src={avatarUrl} 
                alt="Avatar Preview"
                className="w-full h-full drop-shadow-2xl"
                style={{ filter: 'drop-shadow(0 0 20px rgba(147, 51, 234, 0.5))' }}
              />
            ) : (
              <div className="w-full h-full bg-purple-600/20 rounded-full flex items-center justify-center">
                <User className="w-1/2 h-1/2 text-purple-400" />
              </div>
            )}
            
            {/* Mood indicator */}
            <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-2xl animate-pulse">
              {behavior === 'sleep' ? '💤' : behavior === 'follow' ? '👀' : '✨'}
            </div>
          </div>

          {/* Behavior label */}
          <div className="absolute bottom-4 px-3 py-1 bg-black/50 rounded-full text-xs text-slate-400">
            {BEHAVIORS[behavior].name} • {size}px • {speed}x speed
          </div>
        </div>
      </div>

      {/* CSS Animations */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-20px); }
        }
        @keyframes bounce {
          0%, 100% { transform: translateY(0) scale(1); }
          50% { transform: translateY(-30px) scale(1.1); }
        }
        @keyframes spin {
          from { transform: rotate(0deg) translateX(50px) rotate(0deg); }
          to { transform: rotate(360deg) translateX(50px) rotate(-360deg); }
        }
      `}</style>
    </div>
  );
}
